### ISSUE TITLE
How to reset clearml-session arguments to default?

### ISSUE THREAD

**Issue by meanna** [allegroai/clearml-session#16]
I messed up with the arguments of clearml-session and want to reset all to default.
Is there a way to do that?

**Comment by jkhenning** [comment]
Hi @meanna, do you mean during the session execution?

**Comment by meanna** [comment]
Hi  @jkhenning, yes when I call clearml-session but any method to do it would be useful too.

**Comment by jkhenning** [comment]
Well, the most simple way is to delete the clearml-session state cache file, usually located in `~/.clearml_session.json`

**Comment by meanna** [comment]
Got it. Thank you!
