### ISSUE TITLE
noninteractive mode

### ISSUE THREAD

**Issue by akfmdl** [allegroai/clearml-session#17]
Hello clearml team! could you guys add this feature?

If i add '--noninteractive' in clearml-session command, run it directly without asking any choices like 'Use previous queue?' and 'Launch interactive session [Y]/n? '.

**Comment by jkhenning** [comment]
Hi @akfmdl,

So the answer to all the default interactive questions in this mode will be always "yes"?

**Comment by akfmdl** [comment]
Yes that would be good

**Comment by akfmdl** [comment]
> Hi @akfmdl,
> 
> 
> 
> So the answer to all the default interactive questions in this mode will be always "yes"?

Yeah that would be good

**Comment by jkhenning** [comment]
Hi @akfmdl,

I think traditionally this is simply called `--yes` or `-y` as it assumes all your answers are "yes" 🙂

**Comment by akfmdl** [comment]
> 

great! then you will add '--yes' argument instead of '--noninteractive'?

**Comment by akfmdl** [comment]
Thank you @jkhenning !

**Comment by jkhenning** [comment]
@akfmdl just updating this has been included in the latest version v0.6.0
