### ISSUE TITLE
[Feature] SSH passwordless approach

### ISSUE THREAD

**Issue by elgalu** [allegroai/clearml-session#4]
Would it be possible that, instead of relying on user provided or randomly generated SSH passwords, rather instead creating a one-time ssh private key that your API can securely upload to ClearML backend and then drop it into the running K8s pod so only that user can SSH there? 

Slightly related, how EC2 instance connect solves avoiding passwords or manually managing ssh keys:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Connect-using-EC2-Instance-Connect.html

**Comment by jkhenning** [comment]
Hi @elgalu,

`clearml-session` will always generates a new SSH key and places it on the task, specifically to be used by the agent running the task (on the pod, if using k8s) - so I think what you're looking for is already there?
